//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int LoginLogID { get; set; }
        public System.DateTime LoginDate { get; set; }
        public int ClientLoginID { get; set; }
    
        public virtual ClientLogin ClientLogin { get; set; }
    }
}
