//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPhase
    {
        public int ProjectPhaseID { get; set; }
        public string ProjectPhaseDescription { get; set; }
        public int ProjectPhaseStatusID { get; set; }
        public System.DateTime ProjectPhaseStartDate { get; set; }
        public System.DateTime ProjectPhaseEndDate { get; set; }
        public int ProjectPhaseTypeID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectPhaseStatu ProjectPhaseStatu { get; set; }
        public virtual ProjectPhaseType ProjectPhaseType { get; set; }
    }
}
