//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPhaseStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectPhaseStatu()
        {
            this.ProjectPhases = new HashSet<ProjectPhase>();
        }
    
        public int ProjectPhaseStatusID { get; set; }
        public string ProjectPhaseStatusDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPhase> ProjectPhases { get; set; }
    }
}
