//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return
    {
        public int ReturnID { get; set; }
        public string ReturnDescription { get; set; }
        public int ClientQuotationID { get; set; }
    
        public virtual ClientQuotation ClientQuotation { get; set; }
    }
}
