//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientLogin()
        {
            this.LoginLogs = new HashSet<LoginLog>();
            this.Notifcations = new HashSet<Notifcation>();
        }
    
        public int ClientLoginID { get; set; }
        public int ClientID { get; set; }
        public string ClientUsername { get; set; }
        public string ClientPassword { get; set; }
        public System.DateTime ClientLastLogin { get; set; }
        public int AccessLevelID { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginLog> LoginLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifcation> Notifcations { get; set; }
    }
}
