//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int ContactPersonID { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonJobDescription { get; set; }
        public int ContactPersonPhoneNumber { get; set; }
        public string ContactPersonEmailAddress { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
