//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTypePrice
    {
        public int JobTypePriceID { get; set; }
        public decimal JobTypePriceAmount { get; set; }
        public System.DateTime JobTypePriceDate { get; set; }
        public int JobTypeID { get; set; }
    
        public virtual JobType JobType { get; set; }
    }
}
