//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifcation
    {
        public int NotificationID { get; set; }
        public string NotificationMessage { get; set; }
        public int NotificationStatusID { get; set; }
        public Nullable<int> EmployeeLoginID { get; set; }
        public Nullable<int> ClientLoginID { get; set; }
    
        public virtual ClientLogin ClientLogin { get; set; }
        public virtual EmployeeLogin EmployeeLogin { get; set; }
        public virtual NotificationStatu NotificationStatu { get; set; }
    }
}
