//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductClientQuotationLine
    {
        public int ClientQuotationID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
    
        public virtual ClientQuotation ClientQuotation { get; set; }
        public virtual Product Product { get; set; }
    }
}
