//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int ProductPriceID { get; set; }
        public decimal ProductPriceAmount { get; set; }
        public System.DateTime ProductPriceDate { get; set; }
        public int ProductID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
