//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectRequest()
        {
            this.ClientQuotations = new HashSet<ClientQuotation>();
            this.Projects = new HashSet<Project>();
        }
    
        public int ProjectRequestID { get; set; }
        public string ProjectRequestDescription { get; set; }
        public System.DateTime ProjectRequestDate { get; set; }
        public int ProjectRequestTypeID { get; set; }
        public int ProjectRequestStatusID { get; set; }
        public int AddressID { get; set; }
        public int ClientID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientQuotation> ClientQuotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ProjectRequestStatu ProjectRequestStatu { get; set; }
        public virtual ProjectRequestType ProjectRequestType { get; set; }
    }
}
