//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemovedEquipment
    {
        public int RemovedEquipmentID { get; set; }
        public string RemovedEquipmenedDescription { get; set; }
        public string RemovedEquipmentCondition { get; set; }
        public int EquipmentID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
