//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierReturn
    {
        public int SupplierReturnID { get; set; }
        public string SupplierReturnDescription { get; set; }
        public int PurchaseOrderID { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
