//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight_Prototype_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleMake { get; set; }
        public System.DateTime VehicleYear { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string VehicleRegistration { get; set; }
        public int VehicleStatusID { get; set; }
        public int VehicleTypeID { get; set; }
    
        public virtual VehicleStatu VehicleStatu { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
